version: 2
jobs:
  coding_standards_unit_tests:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
        environment:
          MYSQL_HOST=127.0.0.1
          MYSQL_PORT=3306
          MYSQL_USER=root
          MYSQL_PASSWORD=
          MYSQL_ALLOW_EMPTY_PASSWORD=true
      - image: circleci/mysql:5.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: MySQL Database
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client
            sudo -E docker-php-ext-install mysqli
            mysql -u root -e "CREATE DATABASE wp_tests"
      - restore_cache:
          keys:
            - cache-{{ checksum "composer.lock" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Composer Packages
          command: composer install
      - run:
          name: Install Node Packages
          command: sudo npm install --only=dev --unsafe-perm
      - run:
          name: Install WordPress Coding Standards
          command: vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
      - save_cache:
          key: cache-{{ checksum "composer.lock" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - vendor
            - node_modules
            - web/wp
            - web/wp-content/plugins
      - run:
          name: PHPCS Test
          command: vendor/bin/phpcs
      - run:
          name: Unit Tests
          command: vendor/bin/phpunit
      - run:
          name: Lint JavaScript
          command: npm run lint-js
      - run:
          name: Lint CSS
          command: npm run lint-css
workflows:
  version: 2
  tests:
    jobs:
      - coding_standards_unit_tests:
          filters:
            branches:
              only:
                - master
